server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: furniture
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

